database:
  host: localhost
  port: 5432
  database: minecraft
  username: postgres
  password: postgres

message:
  prefix: "§e§lLegendGroups §7| "
  rankCommand:
    line_1: "Du hast folgende Ränge:"
    line_2: "%rank% -> %duration%"
  gui:
    firstPage: "Erste Seite"
    previousPage: "Vorherige Seite"
    nextPage: "Nächste Seite"
    lastPage: "Letzte Seite"
    exit: "Exit"
    return: "Zurück"
    groupItemName: "Gruppen"
    playerItemName: "Spieler"
    ownerGroupsItemName: "Gruppen"
    ownerPermissionsItemName: "Permissions"
    groupsAddItemName: "§aGruppe Hinzufügen"
    permissionsAddItemName: "§aPermission Hinzufügen"
    ownerSettingsItemName: "§eEinstellungen"
  lore:
    removeLore: "Rechtsclick zum Entfernen"
  error:
    ownerNotFound: "Could not Load Permission Owner"
    commandUsage: "Benutze /legendgroups editor für den Editor"
